[package]
name = "deltav"
version = "0.1.0"
authors = ["Hunter Mellema"]
license = "MIT/Apache-2.0"

[dependencies]
structopt = { version = "0.2", default-features = false }
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"